# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title Border effect
#'@description This function calculate the effect of border on mouvement
#' 
#' @param ui_land_width (unsigned int) width of landscape.
#' @param ui_land_heigth (unsigned int) heigth of landscape.
#' @param d_sigma (double) repulsif effect adaptor
#' @param d_pos_x (double) position in x
#' @param d_pos_y (double) position in y
#' @param ad_effect_xy (double[2]) effect in x and y
#' @export
border_effect <- function(ui_width, ui_heigth, d_sigma, d_pos_x, d_pos_y) {
    .Call('_cervideDS_border_effect', PACKAGE = 'cervideDS', ui_width, ui_heigth, d_sigma, d_pos_x, d_pos_y)
}

#' @title Distance to point
#' @description Give distance a point to point and derivate in x and y
#' 
#' @param x (double) x of first point 
#' @param y (double) y of first point 
#' @param x1 (vector) x1 of second point 
#' @param y1 (vector) y1 of second point
#' @return (vector) distance to segment (dist),
#'                  derivate in x (dx),
#'                  derivate in y (dy)
#' @export
distance2point <- function(x, y, x1, y1) {
    .Call('_cervideDS_distance2point', PACKAGE = 'cervideDS', x, y, x1, y1)
}

#' @title shoter distance
#' @description Give shoter distance a point to extrem point of segment and 
#'              derivate in x and y
#' 
#' @param x (double) x of point 
#' @param y (double) y of point 
#' @param x1 (vector) x1 of segment 
#' @param y1 (vector) y1 of segment
#' @param x2 (vector) x2 of segment
#' @param y2 (vector) y2 of segment
#' @return (vector) distance to segment (dist),
#'                  derivate in x (dx),
#'                  derivate in y (dy)
#' @export
shorter_distance <- function(x, y, x1, y1, x2, y2) {
    .Call('_cervideDS_shorter_distance', PACKAGE = 'cervideDS', x, y, x1, y1, x2, y2)
}

#' @title Distance to Segment
#' @description Give distance a point to segment and derivate in x and y
#' 
#' @param x (double) x of point 
#' @param y (double) y of point 
#' @param x1 (vector) x1 of segment 
#' @param y1 (vector) y1 of segment
#' @param x2 (vector) x2 of segment
#' @param y2 (vector) y2 of segment
#' @return (vector) distance to segment (dist),
#'                  derivate in x (dx),
#'                  derivate in y (dy)
#' @export
distance2segment <- function(x, y, x1, y1, x2, y2) {
    .Call('_cervideDS_distance2segment', PACKAGE = 'cervideDS', x, y, x1, y1, x2, y2)
}

#' @title potential function
#' @description potential function
#' 
#' @param alpha_t (double)
#' @param beta (double) spatial display of potential
#' @param dist (double) distance 
#' @param power (double)
#' @return (double) potential
#' @export
potential_func <- function(alpha_t, beta, dist, power) {
    .Call('_cervideDS_potential_func', PACKAGE = 'cervideDS', alpha_t, beta, dist, power)
}

#' @title gradient potential function
#' @description Fonction gradient du potentiel précédent
#' 
#' @param alpha_t (double)
#' @param beta (double) spatial display of potential
#' @param dist (double) distance 
#' @param power (double)
#' @param deriv (double)
#' @return (double) gradiant of potential
#' @export
grad_potential_func <- function(alpha_t, beta, dist, power, deriv) {
    .Call('_cervideDS_grad_potential_func', PACKAGE = 'cervideDS', alpha_t, beta, dist, power, deriv)
}

#' @title alpha function
#' @description evolution of maximum of potential in time
#' 
#' @param alpha1 (double) maximum potential amplitude
#' @param alpha2 (double) spatial display of potential in time
#' @param alpha3 (double) time when potential amplitude is maximum
#' @return (double) miximum of potential at t
#' @export
alpha_func <- function(alpha1, alpha2, alpha3, t) {
    .Call('_cervideDS_alpha_func', PACKAGE = 'cervideDS', alpha1, alpha2, alpha3, t)
}

#' @title effect potential
#' 
#' @param nm_coords_rep (NumericMatrix) all coordinates of repulsif segment 
#'                                      Matrix N*4 (x1,y1,x2,y2)
#' @param nv_coords_point (NumericVector) coordinates of point (x,y)
#' @param bound (NumericVector) limit of effect potential ("min", "max")
#' @param alpha (double) potential amplitude
#' @param beta (double) spatial display of potential
#' @param power (double)
#' @param b_sum_sub (bool) use +gradiant(true) or -gradiant(false) (not effect 
#'        on bound)
#' @return (NumericVector) effect potential in x and y (['x'];['y'])
#' @export
potential_effect <- function(nm_coords_element, nv_coords_point, bound, alpha, beta, power, b_sum_sub) {
    .Call('_cervideDS_potential_effect', PACKAGE = 'cervideDS', nm_coords_element, nv_coords_point, bound, alpha, beta, power, b_sum_sub)
}

#' @title repulsive effect
#' @description Give effect on x and y of all replusive elements 
#' 
#' @param nm_coords_rep (NumericMatrix) all coordinates of repulsif segment 
#'                                      Matrix N*4 (x1,y1,x2,y2)
#' @param nv_coords_point (NumericVector) coordinates of point (x,y)
#' @param alpha1 (double) maximum potential amplitude
#' @return (NumericVector) repulsif effect in x and y (['x'];['y'])
#' @export
repulsive_effect <- function(nm_coords_rep, nv_coords_point, alpha1) {
    .Call('_cervideDS_repulsive_effect', PACKAGE = 'cervideDS', nm_coords_rep, nv_coords_point, alpha1)
}

#' @title attractive effect
#' @description Give effect on x and y of all attractive elements 
#' 
#' @param nm_coords_attrac (NumericMatrix) all coordinates of attractive 
#'                                         segment matrix N*4 (x1,y1,x2,y2)
#' @param nv_coords_point (NumericVector) coordinates of point (x,y)
#' @param alpha1 (double) maximum potential amplitude
#' @return (NumericVector) attractive effect in x and y (['x'];['y'])
#' @export
attractive_effect <- function(nm_coords_attrac, nv_coords_point, alpha1) {
    .Call('_cervideDS_attractive_effect', PACKAGE = 'cervideDS', nm_coords_attrac, nv_coords_point, alpha1)
}

#' @title all effect
#' @description Give complete effect of landscape on x and y
#' 
#' @param nv_coords_point (NumericVector) coordinates of point (x,y)
#' @param ui_land_width (unsigned int) width of landscape.
#' @param ui_land_heigth (unsigned int) heigth of landscape.
#' @param d_sigma (double) repulsif effect adaptor
#' @param nm_coords_attrac (NumericMatrix) all coordinates of attractive 
#'                                         segment matrix N*4 (x1,y1,x2,y2)
#' @param alpha_a (double) maximum potential amplitude of attrativity
#' @param nm_coords_rep (NumericMatrix) all coordinates of repulsif segment 
#'                                      Matrix N*4 (x1,y1,x2,y2)
#' @param alpha_r (double) maximum potential amplitude of repulsivity
#' @param time_step (double) step of time
#' @return (NumericVector) effect in x and y (['x'];['y'])
#' @export
all_effect <- function(nv_coords_point, ui_width, ui_heigth, d_sigma, nm_coords_attrac, alpha_a, nm_coords_rep, alpha_r, time_step) {
    .Call('_cervideDS_all_effect', PACKAGE = 'cervideDS', nv_coords_point, ui_width, ui_heigth, d_sigma, nm_coords_attrac, alpha_a, nm_coords_rep, alpha_r, time_step)
}

#' @title diffusion
#' @description calculate the diffusion
#' 
#' @param d_sigma (double)
#' @param time_step (double) step of time
#' @return (double) diffusion
#' @export
diffusion <- function(d_sigma, time_step) {
    .Call('_cervideDS_diffusion', PACKAGE = 'cervideDS', d_sigma, time_step)
}

